export const ADD_SUCCESS = "@@admin/ADD_SUCCESS"
export const ADD_FAILURE = "@@admin/ADD_FAILURE"
export const ADD_REQUEST = "@@admin/ADD_REQUEST"

export const GET_VOLUNTEERS_REQUEST = "@@admin/GET_VOLUNTEERS_REQUEST"
export const GET_VOLUNTEERS_FAILURE = "@@admin/GET_VOLUNTEERS_FAILURE"
export const GET_VOLUNTEERS_SUCCESS = "@@admin/GET_VOLUNTEERS_SUCCESS"

export const GET_HOSPITALS_REQUEST = "@@admin/GET_HOSPITALS_REQUEST"
export const GET_HOSPITALS_FAILURE ="@@admin/GET_HOSPITALS_FAILURE"
export const GET_HOSPITALS_SUCCESS ="@@admin/GET_HOSPITALS_SUCCESS"

export const DELETE_REQUEST ="@@admin/DELETE_REQUEST"
export const DELETE_FAILURE ="@@admin/DELETE_FAILURE"
export const DELETE_SUCCESS ="@@admin/DELETE_SUCCESS"